services:
  medibridge-next:
    container_name: medibridge-next
    restart: always
    image: node:24.12.0
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:4001
      - REACT_APP_API_GRAPHQL_URL=http://localhost:4001/graphql
      - NEXT_PUBLIC_API_WS=ws://localhost:4001/graphql
      - API_INTERNAL_GRAPHQL_URL=http://medibridge-api:5885/graphql
      - API_PROXY_URL=http://medibridge-api:5885
      - TZ=Asia/Seoul
    volumes:
      - ./:/usr/src/medibridge-next
    working_dir: /usr/src/medibridge-next
    networks:
      - medibridge-shared
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  medibridge-shared:
    external: true
    name: medibridge-shared




#medi-bridge-next: localhost:4000 <==> container:3000
#medibridge-api: localhost:4001 <==> container:3007
#medibridge-batch: localhost:4002 <==> container:3008
